import re
from fpdf import FPDF

def extract_skills(text):
    # Basic keyword extraction for visualization
    common_skills = [
        "python", "java", "sql", "react", "aws", "docker", "kubernetes", "machine learning",
        "data analysis", "project management", "communication", "leadership", "agile", "scrum",
        "html", "css", "javascript", "typescript", "figma", "design", "marketing", "sales",
        "finance", "accounting", "hr", "recruiting", "tensorflow", "pytorch", "pandas", "numpy",
        "c++", "c", "c#", "ruby", "go", "rust", "tableau", "power bi", "excel"
    ]
    
    found_skills = []
    text_lower = text.lower()
    
    for skill in common_skills:
        if re.search(r'\b' + re.escape(skill) + r'\b', text_lower):
            found_skills.append(skill.title())
            
    return list(set(found_skills))

# --- PDF GENERATION WITH FULL REPORT ---

def clean_text(text):
    """
    Fixes encoding issues. FPDF (standard) only supports Latin-1.
    Replaces unsupported characters (like emojis/smart quotes) to prevent crashes.
    """
    if not text: return ""
    # Encode to latin-1, replacing errors with '?', then decode back to string
    text = text.replace('’', "'").replace('“', '"').replace('”', '"').replace('–', '-')
    return text.encode('latin-1', 'replace').decode('latin-1')

def generate_pdf_report(username, role, score, feedback, resume_skills, missing_skills, category, interview_q, market_analysis, roadmap):
    class PDF(FPDF):
        def header(self):
            self.set_font('Arial', 'B', 15)
            self.cell(0, 10, 'SmartRecruit Platinum Analysis Report', 0, 1, 'C')
            self.ln(5)

        def footer(self):
            self.set_y(-15)
            self.set_font('Arial', 'I', 8)
            self.set_text_color(128)
            self.cell(0, 10, 'Generated by SmartRecruit | Developed by Karunya K. P.', 0, 0, 'C')

    pdf = PDF()
    
    # --- PAGE 1: SUMMARY & SCORES ---
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 8, txt=clean_text(f"Candidate: {username}"), ln=True)
    pdf.cell(200, 8, txt=clean_text(f"Target Role: {role}"), ln=True)
    pdf.cell(200, 8, txt=clean_text(f"Profile Category: {category}"), ln=True) 
    pdf.ln(5)
    
    # Score
    pdf.set_font("Arial", 'B', size=24)
    pdf.set_text_color(79, 70, 229) # Purple
    pdf.cell(200, 20, txt=f"ATS Match Score: {score}%", ln=True, align='C')
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)
    
    # Feedback
    pdf.set_font("Arial", 'B', size=14)
    pdf.cell(200, 10, txt="AI Analysis & Feedback", ln=True)
    pdf.set_font("Arial", size=11)
    pdf.multi_cell(0, 7, txt=clean_text(feedback.replace("*", "").replace("#", "")))
    pdf.ln(10)
    
    # Skills Table
    col_width = 90
    pdf.set_font("Arial", 'B', size=12)
    pdf.cell(col_width, 10, "Matched Skills", border=1)
    pdf.cell(col_width, 10, "Missing Skills", border=1)
    pdf.ln()
    pdf.set_font("Arial", size=10)
    
    if resume_skills is None: resume_skills = []
    if missing_skills is None: missing_skills = []
    max_len = max(len(resume_skills), len(missing_skills))
    
    for i in range(max_len):
        m_skill = resume_skills[i] if i < len(resume_skills) else ""
        miss_skill = missing_skills[i] if i < len(missing_skills) else ""
        
        pdf.set_text_color(0, 100, 0) # Green
        pdf.cell(col_width, 8, clean_text(m_skill), border=1)
        pdf.set_text_color(150, 0, 0) # Red
        pdf.cell(col_width, 8, clean_text(miss_skill), border=1)
        pdf.ln()
    pdf.set_text_color(0, 0, 0)

    # --- PAGE 2: INTERVIEW PREP ---
    pdf.add_page()
    pdf.set_font("Arial", 'B', size=16)
    pdf.cell(0, 10, "Interview Preparation", 0, 1, 'L')
    pdf.ln(5)
    
    pdf.set_font("Arial", size=11)
    pdf.multi_cell(0, 7, txt=clean_text(interview_q.replace("*", "").replace("#", "")))

    # --- PAGE 3: STRATEGIC INSIGHTS ---
    pdf.add_page()
    pdf.set_font("Arial", 'B', size=16)
    pdf.cell(0, 10, "Strategic Insights", 0, 1, 'L')
    pdf.ln(5)
    
    pdf.set_font("Arial", 'B', size=14)
    pdf.cell(0, 10, "Market Value & Trends", 0, 1, 'L')
    pdf.set_font("Arial", size=11)
    pdf.multi_cell(0, 7, txt=clean_text(market_analysis.replace("*", "").replace("#", "")))
    pdf.ln(10)
    
    pdf.set_font("Arial", 'B', size=14)
    pdf.cell(0, 10, "Upskilling Roadmap", 0, 1, 'L')
    pdf.set_font("Arial", size=11)
    pdf.multi_cell(0, 7, txt=clean_text(roadmap.replace("*", "").replace("#", "")))
    
    return pdf.output(dest='S').encode('latin-1', 'replace')
